title: 我们的甜蜜时光
<<<<<<< HEAD
author: 世涛 & 小静
=======
author: 石涛 & 心爱的她
>>>>>>> 21ef48183dc32d6e692e48b7b2b092f605219958
email: your@email.com
description: >-
  记录我们的日常生活、爱情故事和甜蜜冒险。❤️
baseurl: ""
url: "https://shitaolol.github.io"
twitter_username: shitaolol
github_username: shitaolol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

# Custom navigation
header_pages:
  - about.markdown
  - gallery.md
  - archive.md

# Google Fonts
google_fonts: "Inter|Noto+Sans+SC:300,400,700|Lobster"

# Minima customization
minima:
  date_format: "%Y年%m月%d日"
  skin: auto

# 自定义配置
start_date: "2024-08-31"
love_quote: "每一天都是爱你的新理由 ❤️"

# 社交媒体
social_links:
  github: shitaolol
  email: your@email.com

# 图片设置
default_image: "/assets/images/default-memory.jpg"