# 情侣博客配置
title: "世涛和小静的甜蜜时光"
author: "世涛 & 小静"
email: "shitao@example.com"
description: "记录我们的日常生活、爱情故事和甜蜜冒险 ❤️"

# 网站设置
baseurl: ""
url: "https://shitaolol.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# 导航页面
header_pages:
  - about.markdown
  - gallery.md
  - archive.md

# 主题设置
minima:
  date_format: "%Y年%m月%d日"
  skin: auto

# 自定义配置
start_date: "2024-08-31"
love_quote: "每一天都是爱你的新理由 ❤️"

# 社交媒体
social_links:
  github: Shitaolol
  email: shitao@example.com

# 默认图片
default_image: "/assets/images/default-memory.svg"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md
  - DEPLOY.md
  - COMPLETE_SETUP.md
  - cleanup_and_push.bat
  - upload_clean.bat